/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PromptResultService } from "../promptResult.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PromptResultCreateInput } from "./PromptResultCreateInput";
import { PromptResult } from "./PromptResult";
import { PromptResultFindManyArgs } from "./PromptResultFindManyArgs";
import { PromptResultWhereUniqueInput } from "./PromptResultWhereUniqueInput";
import { PromptResultUpdateInput } from "./PromptResultUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PromptResultControllerBase {
  constructor(
    protected readonly service: PromptResultService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PromptResult })
  @nestAccessControl.UseRoles({
    resource: "PromptResult",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PromptResultCreateInput,
  })
  async createPromptResult(
    @common.Body() data: PromptResultCreateInput
  ): Promise<PromptResult> {
    return await this.service.createPromptResult({
      data: {
        ...data,

        prompt: data.prompt
          ? {
              connect: data.prompt,
            }
          : undefined,

        transcription: data.transcription
          ? {
              connect: data.transcription,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        prompt: {
          select: {
            id: true,
          },
        },

        result: true,
        status: true,

        transcription: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PromptResult] })
  @ApiNestedQuery(PromptResultFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PromptResult",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async promptResults(@common.Req() request: Request): Promise<PromptResult[]> {
    const args = plainToClass(PromptResultFindManyArgs, request.query);
    return this.service.promptResults({
      ...args,
      select: {
        createdAt: true,
        id: true,

        prompt: {
          select: {
            id: true,
          },
        },

        result: true,
        status: true,

        transcription: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PromptResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PromptResult",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async promptResult(
    @common.Param() params: PromptResultWhereUniqueInput
  ): Promise<PromptResult | null> {
    const result = await this.service.promptResult({
      where: params,
      select: {
        createdAt: true,
        id: true,

        prompt: {
          select: {
            id: true,
          },
        },

        result: true,
        status: true,

        transcription: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PromptResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PromptResult",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PromptResultUpdateInput,
  })
  async updatePromptResult(
    @common.Param() params: PromptResultWhereUniqueInput,
    @common.Body() data: PromptResultUpdateInput
  ): Promise<PromptResult | null> {
    try {
      return await this.service.updatePromptResult({
        where: params,
        data: {
          ...data,

          prompt: data.prompt
            ? {
                connect: data.prompt,
              }
            : undefined,

          transcription: data.transcription
            ? {
                connect: data.transcription,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          prompt: {
            select: {
              id: true,
            },
          },

          result: true,
          status: true,

          transcription: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PromptResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PromptResult",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePromptResult(
    @common.Param() params: PromptResultWhereUniqueInput
  ): Promise<PromptResult | null> {
    try {
      return await this.service.deletePromptResult({
        where: params,
        select: {
          createdAt: true,
          id: true,

          prompt: {
            select: {
              id: true,
            },
          },

          result: true,
          status: true,

          transcription: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
